"""
JSON extraction and validation utilities.

Handles AI responses that may contain markdown fences, extra text,
or other non-JSON content wrapping the actual JSON payload.
Also provides repair for duplicated text and deduplication of list fields
commonly returned by local AI models.
"""
import json
import re


# Fields that contain lists of strings and should be deduplicated.
_LIST_FIELDS = {
    "scenes",
    "locations",
    "objects",
    "actions",
    "visible_text",
    "important_events",
    "uncertainties",
    "chronological_scenes",
    "important_locations",
    "important_objects",
    "actions_and_events",
    "major_changes",
}


def _normalize_text(text: str) -> str:
    """Normalize whitespace and case for deduplication comparison."""
    return " ".join(text.lower().split())


def _deduplicate_list(items: list) -> list:
    """Remove duplicate text entries from a list while preserving order.

    Only string items are checked for duplicates; non-string items
    (e.g. nested dicts) are always kept.
    """
    result = []
    seen = set()

    for item in items:
        if isinstance(item, str):
            key = _normalize_text(item)
            if key in seen:
                continue
            seen.add(key)
        result.append(item)

    return result


def clean_json_data(data):
    """Recursively deduplicate list fields in parsed JSON data.

    Walks the entire JSON tree and deduplicates any list field whose
    key is in _LIST_FIELDS.  Non-list values and unknown keys are
    left untouched.

    Args:
        data: Parsed JSON (dict, list, or scalar).

    Returns:
        The cleaned data (modified in place for dicts).
    """
    if isinstance(data, dict):
        for key, value in data.items():
            if key in _LIST_FIELDS and isinstance(value, list):
                data[key] = _deduplicate_list(value)
            else:
                data[key] = clean_json_data(value)
        return data

    if isinstance(data, list):
        return [
            clean_json_data(item) if isinstance(item, (dict, list)) else item
            for item in data
        ]

    return data


def repair_duplicated_text(text: str) -> str:
    """Attempt to repair raw AI responses with duplicated text blocks.

    Some local models produce output where a large chunk of the JSON
    response is repeated verbatim (e.g. the model "stutters" and
    emits the same block twice).  This makes the overall response
    invalid JSON even though each individual copy is fine.

    Strategy:
    1. Find the outermost ``{ ... }`` span.
    2. If that span is already valid JSON, return it as-is.
    3. Otherwise, try progressively removing a duplicated suffix
       by looking for the longest repeated tail that, once removed,
       yields valid JSON.
    4. As a last resort, try to find a *complete* valid JSON object
       starting from each ``{`` in the text.

    Returns:
        The (possibly repaired) text.  If no repair is possible the
        original text is returned unchanged.
    """
    text = text.strip()

    # Quick exit: already valid
    try:
        json.loads(text)
        return text
    except json.JSONDecodeError:
        pass

    # Locate outermost braces
    first_brace = text.find('{')
    last_brace = text.rfind('}')
    if first_brace == -1 or last_brace == -1 or last_brace <= first_brace:
        return text

    candidate = text[first_brace:last_brace + 1]

    # Already valid after trimming surrounding text?
    try:
        json.loads(candidate)
        return candidate
    except json.JSONDecodeError:
        pass

    # --- Heuristic: detect a repeated JSON block ----------------------
    # Look for two copies of a large-ish substring.  We try to split
    # the candidate at every ``}\s*{`` boundary (which is characteristic
    # of two JSON objects concatenated together) and keep the first
    # valid one.
    split_points = [m.start() for m in re.finditer(r'\}\s*\{', candidate)]
    for sp in split_points:
        fragment = candidate[:sp + 1]  # up to and including the '}'
        try:
            json.loads(fragment)
            return fragment
        except json.JSONDecodeError:
            continue

    # --- Heuristic: progressive brace-matching from the start ---------
    # Walk from the first '{' and track brace depth.  Every time depth
    # returns to 0 we have a complete object — try to parse it.
    depth = 0
    for i, ch in enumerate(candidate):
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                fragment = candidate[:i + 1]
                try:
                    json.loads(fragment)
                    return fragment
                except json.JSONDecodeError:
                    break  # first balanced span didn't parse, give up

    return text


import ast


def _strip_thinking_tags(text: str) -> str:
    """Remove <think>...</think> blocks generated by reasoning models (DeepSeek-R1, etc.)."""
    return re.sub(r'<think>[\s\S]*?</think>', '', text, flags=re.IGNORECASE).strip()


def _clean_json_comments(text: str) -> str:
    """Remove single-line (// or #) and multi-line (/* */) comments from JSON text."""
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith('//') or (stripped.startswith('#') and not stripped.startswith('#!')):
            continue
        # Check inline // comment (avoid matching :// in URLs)
        idx = line.find('//')
        if idx > 0 and line[idx - 1] != ':':
            line = line[:idx]
        lines.append(line)
    result = '\n'.join(lines)
    # Remove /* ... */ multi-line comments
    result = re.sub(r'/\*[\s\S]*?\*/', '', result)
    return result


def _clean_trailing_commas(text: str) -> str:
    """Remove trailing commas before closing braces and brackets."""
    return re.sub(r',\s*([}\]])', r'\1', text)


def _clean_python_literals(text: str) -> str:
    """Convert Python True/False/None literals to JSON true/false/null."""
    text = re.sub(r'\bTrue\b', 'true', text)
    text = re.sub(r'\bFalse\b', 'false', text)
    text = re.sub(r'\bNone\b', 'null', text)
    return text


def _repair_unclosed_braces(text: str) -> str:
    """Attempt to repair truncated JSON by closing any open strings, brackets, and braces."""
    stack = []
    in_string = False
    escape = False

    for ch in text:
        if escape:
            escape = False
            continue
        if ch == '\\':
            if in_string:
                escape = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if not in_string:
            if ch in ('{', '['):
                stack.append('}' if ch == '{' else ']')
            elif ch in ('}', ']'):
                if stack and stack[-1] == ch:
                    stack.pop()

    res = text
    if in_string:
        res += '"'

    # Strip any trailing comma before appending closing brackets/braces
    res = re.sub(r',\s*$', '', res.rstrip())

    while stack:
        closing = stack.pop()
        res += closing

    return res


def _clean_and_repair_json_str(candidate: str) -> str | None:
    """Attempt to parse candidate and return a normalized, valid JSON string.

    Tries in sequence:
    1. Direct JSON parse (strict=False to allow unescaped newlines/tabs).
    2. Stripping comments, trailing commas, and Python literals (True/False/None).
    3. Python literal eval for single-quoted dict/list outputs.
    4. Auto-closing truncated brackets/braces.

    Returns:
        A valid JSON string if successful, or None.
    """
    if not candidate or not candidate.strip():
        return None
    candidate = candidate.strip()

    # 1. Direct standard parse
    try:
        val = json.loads(candidate, strict=False)
        if isinstance(val, (dict, list)):
            return candidate
    except Exception:
        pass

    # 2. Clean comments, trailing commas, Python literals
    cleaned = _clean_json_comments(candidate)
    cleaned = _clean_trailing_commas(cleaned)
    cleaned = _clean_python_literals(cleaned)
    try:
        val = json.loads(cleaned, strict=False)
        if isinstance(val, (dict, list)):
            return cleaned
    except Exception:
        pass

    # 3. Try ast.literal_eval for single-quoted Python dict/list literals
    try:
        parsed_ast = ast.literal_eval(candidate)
        if isinstance(parsed_ast, (dict, list)):
            return json.dumps(parsed_ast, ensure_ascii=False)
    except Exception:
        pass

    # 4. Try repairing truncated JSON (unclosed strings, brackets, braces)
    try:
        repaired = _repair_unclosed_braces(cleaned)
        val = json.loads(repaired, strict=False)
        if isinstance(val, (dict, list)):
            return repaired
    except Exception:
        pass

    return None


def _extract_from_fences(text: str) -> str | None:
    """Extract JSON from markdown code fences with flexible regex and repair."""
    fence_patterns = [
        # Standard closed fence: ```json ... ``` (case-insensitive)
        r'```(?:json|json5|javascript|python)?\s*([\s\S]*?)\s*```',
        # Bare closed fence: ``` ... ```
        r'```\s*([\s\S]*?)\s*```',
        # Unclosed fence (model output truncated before closing ```)
        r'```(?:json|json5|javascript|python)?\s*([\s\S]*)$',
    ]
    for pattern in fence_patterns:
        for match in re.finditer(pattern, text, re.IGNORECASE | re.DOTALL):
            candidate = match.group(1).strip()
            if not candidate:
                continue
            repaired = _clean_and_repair_json_str(candidate)
            if repaired is not None:
                return repaired
    return None


def _extract_by_brace_depth(text: str) -> str | None:
    """Find the first complete JSON object or array via brace/bracket depth tracking."""
    openers = []
    for i, ch in enumerate(text):
        if ch in ('{', '['):
            openers.append(i)

    for start in openers:
        open_char = text[start]
        close_char = '}' if open_char == '{' else ']'
        depth = 0
        in_string = False
        escape_next = False

        for i in range(start, len(text)):
            ch = text[i]

            if escape_next:
                escape_next = False
                continue

            if in_string:
                if ch == '\\':
                    escape_next = True
                elif ch == '"':
                    in_string = False
                continue

            if ch == '"':
                in_string = True
            elif ch == open_char:
                depth += 1
            elif ch == close_char:
                depth -= 1
                if depth == 0:
                    candidate = text[start:i + 1]
                    repaired = _clean_and_repair_json_str(candidate)
                    if repaired is not None:
                        return repaired
                    break  # This balanced span failed, try next opener

    # If balanced scan didn't find anything, try from the first '{' with truncated repair
    first_brace = text.find('{')
    if first_brace != -1:
        candidate = text[first_brace:]
        repaired = _clean_and_repair_json_str(candidate)
        if repaired is not None:
            return repaired

    return None


def extract_json_from_text(text: str) -> str | None:
    """Try to extract a JSON object from text that may contain extra content.

    Handles:
    - Pure JSON
    - JSON wrapped in markdown fences (```json ... ``` or unclosed ```json ...)
    - DeepSeek-R1 / thinking models with <think>...</think> tags
    - JSON embedded in surrounding conversational text
    - Trailing commas, comments, and Python literals (True/False/None)
    - Python dict representations with single quotes
    - Truncated JSON missing closing brackets/braces
    - JSON arrays ([...]) as well as objects ({...})
    - Duplicated / repeated JSON blocks (via repair)

    Returns:
        The JSON string if found, or None.
    """
    if not text or not isinstance(text, str):
        return None

    text = text.strip()
    if not text:
        return None

    # Step 0: If thinking tags are present, prioritize extracting from the text AFTER <think>
    if '<think>' in text.lower() and '</think>' in text.lower():
        stripped = _strip_thinking_tags(text)
        if stripped:
            res = extract_json_from_text(stripped)
            if res is not None:
                return res

    # 1. Direct parse / clean
    repaired = _clean_and_repair_json_str(text)
    if repaired is not None:
        return repaired

    # 2. Code fences
    result = _extract_from_fences(text)
    if result is not None:
        return result

    # 3. Depth-balanced extraction
    result = _extract_by_brace_depth(text)
    if result is not None:
        return result

    # 4. Duplicated-text repair as fallback
    dup_repaired = repair_duplicated_text(text)
    if dup_repaired != text:
        repaired = _clean_and_repair_json_str(dup_repaired)
        if repaired is not None:
            return repaired

    return None


def safe_parse_json(text: str) -> tuple[dict | None, str | None]:
    """Try to parse a JSON object from AI response text.

    Applies text repair (for duplicated blocks, trailing commas, comments,
    thinking tags, markdown fences, Python dicts, etc.) and extraction,
    then deduplicates known list fields in the result.

    Returns:
        (parsed_dict, None) on success, or (None, error_message) on failure.
    """
    if not text or not isinstance(text, str) or not text.strip():
        return None, "Empty response from model"

    extracted = extract_json_from_text(text)
    if extracted is None:
        return None, "Could not find valid JSON in response"

    try:
        result = json.loads(extracted, strict=False)
        if not isinstance(result, dict):
            return None, f"Expected JSON object, got {type(result).__name__}"
        result = clean_json_data(result)
        return result, None
    except Exception as e:
        # Fallback to ast.literal_eval if json.loads still choked on something
        try:
            val = ast.literal_eval(extracted)
            if isinstance(val, dict):
                val = clean_json_data(val)
                return val, None
        except Exception:
            pass
        return None, f"JSON parse error: {e}"
